version: '3.7'
services:
  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '8080:8080'
    depends_on:
      - 'frontend'
  frontend:
    build:
      context: ..
      dockerfile: Dockerfile
    restart: always
    environment:
      VITE_STRAPI_URL: '${FRONTEND_STRAPI_URL}'
    ports:
      - '3000:3000'
